name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    # Update to @main or a newer tag to get Node 24 support
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
